###
GET http://localhost:3000/assets

###
POST  http://localhost:3000/assets
Content-Type: application/json

  {
    "id": "asset3",
    "symbol": "B4",
    "price": 100
  }

###
GET http://localhost:3000/wallets

###
POST  http://localhost:3000/wallets
Content-Type: application/json

{
  "id": "wallet3"
}

###
GET http://localhost:3000/wallets/wallet1/assets

###
POST  http://localhost:3000/wallets/wallet1/assets
Content-Type: application/json

{
  "asset_id": "asset2",
  "shares": 10
}

###
POST  http://localhost:3000/orders
Content-Type: application/json

{
  "asset_id": "asset1",
  "wallet_id": "wallet3",
  "shares": 20,
  "price": 5,
  "type": "SELL"
}